'Date, First Name, Last Name, phone, Email, Last Active Date'

import { Table } from 'reactstrap'

export default function ApplicantsDataTable() {
    return (
        <Table hover className='mt-4'>
            <thead>
                <tr>
                    <th>
                        Date
                    </th>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Last Active Date
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        Khan
                    </td>
                    <td>
                        user@gmail.com
                    </td>
                    <td>
                        2/2/1998
                    </td>
                </tr>
            </tbody>
        </Table>
    )
}