import { Table } from 'reactstrap'

export default function DataTable() {
    return (
        <Table hover className='mt-4'>
            <thead>
                <tr>
                    <th>
                        Date
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        ISSN
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Status
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
                <tr>
                    <td>
                        02/02/1999
                    </td>
                    <td>
                        Mark
                    </td>
                    <td>
                        222-445-3437
                    </td>
                    <td>
                        $120
                    </td>
                    <td>
                        active
                    </td>
                </tr>
            </tbody>
        </Table>
    )
}