import {Container} from 'reactstrap'

export default function Page(){
    return(
        <Container className='mt-4'>
            <p>Terms & Conditions</p>
            <p>Notice: A short term loan provides the cash needed to meet an immediate short-term cash flow problem. It is not a solution for longer term financial problems for which longer term financing may be more appropriate. You may want to discuss your financial situation with a nonprofit financial counseling service in your community. You may be charged additional fees if you renew the loan.</p>
            <p>Terms and Conditions of Use</p>
            <p>1. Age Restriction and Acknowledgement BY USING, ACCESSING THE WEBSITE OR ANY MATERIALS OR CONTENT ON WEBSITE, YOU, THE USER ARE REPRESENTING THAT YOU ARE EIGHTEEN YEARS OLD OR OLDER ALL USERS MUST BE AT LEAST 18 YEARS OF AGE OR OLDER THERE ARE NO EXCEPTIONS</p>
            <p>2. Your Acceptance. By using, and by accessing the materials at Websites or interfacing in any matter with the Website and/or visiting this website (collectively, including all content and functionality available through the zimbacash.com domain name, the &ldquo;zimbacash.com&rdquo;, or &ldquo;Site&rdquo;, &ldquo;Website&rdquo; or &ldquo;Company&rdquo;) , you confirm and acknowledge your agreement to (1) these Terms and Conditions Agreement and (2) zimbacash.com&lsquo;s privacy notice, and incorporated here by reference and also incorporated here by reference. If you do not agree to any of these terms, the Company privacy notice, or the Community Guidelines, please do not use, connect, access, or download any content to the zimbacash.com Website. This Terms and Conditions Agreement is an electronic agreement that sets out the Terms and Conditions of the Website and User&lsquo;s use and access of the Website. zimbacash.com d/b/a zimbacash.com reserves the right at its sole discretion, to change, modify, add or remove portions of these Terms and Conditions, at any time. It is your responsibility to check these Terms and Conditions periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms and Conditions. zimbacash.com d/b/a zimbacash.com grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site</p>
            <p>3. Electronic Agreement. This Agreement is an electronic contract that sets out the legally binding terms of your use of the Website. This Agreement may be modified by zimbacash.com by posting on its website from time to time and such modifications to be effective upon posting. This Agreement includes the Privacy Policy and any specific policies regarding Advertisers or Venders and any notices regarding the Website. By accessing the Website, you accept this Agreement and agree to the terms, conditions, and notices contained or referenced herein. </p>
            <p>4. CONSENT TO ELECTRONIC AND TELEPHONE COMMUNICATIONS: The following terms and conditions govern electronic communications in connection with this Agreement and the transaction evidenced hereby (the &ldquo;Consent&rdquo;). By this Agreement, you agree that any notices we are required to make to you may be delivered to you electronically. You agree that any notices we are required to make to you may be delivered to you electronically. You expressly consent to the Company contacting you at any phone number listed on your application or contract, including home address or email address provided on this document, updated by you or provided by your references in the future, or ascertained by Company through its resources. You acknowledge and agree to the following terms and conditions of this Consent and that you have received a copy of this Consent for your records. You agree that:</p>
            <p>Any disclosure, notice, record or other type of information that is provided to you in connection with your transaction with us, including but not limited to, this Agreement, this Consent, the Application, change−in−terms notice, fee and transaction information, statements, delayed disbursement notices, notices of adverse action, state mandated brochures and disclosures, and transaction information (&ldquo;Communications&rdquo;), may be sent to you electronically by posting the information at our web site, provided at the top of this agreement, or by sending it to you by email.</p>
            <p>You agree to provide us with your current email address for notices at the email address or phone number indicated at the top of this agreement. If your email address, telephone number(s), or residence address changes, you must send us a notice of the new address/telephone number(s) by writing to us or sending us an email, at least five (5) days before the change.</p>
            <p>In order to receive electronic communications, you will need a working connection to the Internet and an email account. . Your browser must support the Secure Sockets Layer (SSL) protocol. You must have a printer or sufficient hard drive space available to save the information. If you have a question about your browser and the SSL protocol, please contact your Internet Service Provider or a qualified information technology service provider.</p>
            <p>We may amend (add to, delete or change) the term of this Consent by providing you with advance notice</p>
            <p>5. SMS (TEXT MESSAGING) STATEMENT NOTIFICATIONS DISCLOSURE: This SMS Statement Notifications Disclosure (&ldquo;Disclosure&rdquo;) applies to your account with the Lender if you have elected to receive Short Message Service (SMS) messages.</p>
            <p>As used in this Disclosure, &ldquo;SMS Statement Notifications&rdquo; means any SMS (text message) communications from us to you pertaining to your Agreement, including but not limited to payment information, account information, due dates, delinquent accounts, program updates, promotions, coupons and other marketing messages</p>
            <p>In order to access, view, and retain SMS Statement Notifications that we make available to you, you must have: (1) a SMS−capable mobile phone, (2) an active mobile phone account with a communication service provider; and (3) sufficient storage capacity on your mobile phone.</p>
            <p>All SMS Statement Notifications in electronic format from us to you will be considered &ldquo;in writing&rdquo;.</p>
            <p>There is no service fee for SMS Statement Notifications but you are responsible for any and all charges, including but not limited to fees associated with text messaging, imposed by your communications service provider. Other charges may apply, such charges may include those from your communications service provider. Please consult your mobile service carrier&lsquo;s pricing plan to determine the charges for sending and receiving text messages. These charges will appear on your phone bill. Message frequency depends on account settings.</p>
            <p>Additionally, you agree that we may send any SMS Statement Notifications through your communication service provider in order to deliver them to you and that your communication service provider is acting as your agent in this capacity You agree to provide a valid mobile phone number for these services so that we may send you certain information about your account. Additionally, you agree to indemnify, defend and hold us harmless from and against any and all claims, losses, liability, cost and expenses (including reasonable attorney&lsquo;s fees) arising from your provision of a mobile phone number that is not your own or your violation of applicable federal, state, or local law, regulation or ordinance. Your obligation under this paragraph shall survive termination of this Agreement. SMS Statement Notifications are provided for your convenience only. Receipt of each SMS Statement may be delayed or impacted by factor(s) pertaining to your communications service provider(s). We will not be liable for losses or damages arising from any disclosure of account information to third parties, non−delivery, delayed delivery, misdirected delivery or mishandling of, or inaccurate content in, the SMS Statement Notifications sent by us.</p>
            <p>We may modify or terminate our text messaging services from time to time, for any reason, and without notice, including the right to terminate text messaging with or without notice. Please review these Terms of Use from time to time so that you are timely notified of any changes.</p>
            <p>You agree and consent to be contained by the Company, its agents, employees, attorneys, affiliates, assignees, subsequent creditors, loan servicing companies and third party collectors through the use of email, telephone and/or text or SMS messages to your cellular, home or work phone numbers as well as any other phone numbers you have provided in conjunction with this loan, including the use of automatic dialing systems, autodialers or artificial or pre-recordings.</p>
            <p>6. Privacy Notice. zimbacash.com d/b/a zimbacash.com &lsquo;s Privacy Notice and Privacy Policy (see link) applies to use of this Site, and its terms are made a part of these Terms and Conditions by this reference. Additionally, by using the Site, you acknowledge and agree that Internet transmissions are never completely private or secure. You understand that any message or information you send to the Site may be read or intercepted by others, notwithstanding zimbacash.com d/b/a zimbacash.com &lsquo;s efforts to protect such transmissions.</p>
            <p>You further agree that if zimbacash.com is unable to service and approve your application for any reason, zimbacash.com may refer your application to a third party who shall consider your application as intent to apply for their services. Any services provided or loan issued by a third party shall be serviced entirely by that third party and not by zimbacash.com, and shall be subject to the terms set forth by that third party lender providing the loan or services.</p>
            <p>
            7. Security for the Site. As a condition of your use of this Site, you agree that you will not, and you will not take any action intended to: (a) view, download or access data that is not intended for any party other than you; (b) invade the privacy of, obtain the identity of, or obtain any personal information about any zimbacash.com d/b/a zimbacash.com customer or user of this Site; (c) probe or test the vulnerability of this Site or the zimbacash.com d/b/a zimbacash.com network or breach security or authentication measures without proper authorization; (d) attempt to interfere with service to any user, host or network or otherwise attempt to disrupt our business, including, without limitation, via means of uploading a virus, worm or Trojan horse to this Site, overloading, &ldquo;spamming,&ldquo; or &ldquo;crashing;&ldquo; or (e) send unsolicited mail, including promotions and/or advertising of products and services or execution files. Violations of system or network security may result in civil or criminal liability.
            </p>
            <p>8. Disclaimers of Warranty and General Disclaimers. YOU AGREE THAT YOUR USE OF THE COMPANIE&lsquo;S WEBSITE(S) SHALL BE AT YOUR OWN SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW. THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, ASSIGNEE, AFFILITIES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE, ANY USE OF THE WEBSITE OR ANY COMMUNICATION THAT YOU OR ANY USER MAY HAVE WITH ANY OTHER USER OR PERSONS OR ENTITY REFERENCING SERVICES ON THE WEBSITE. COMPANY MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE WEBSITES CONTENT, THE USER CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY: (a) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE OR ANY COMMUNICATION WITH ANY OTHER USER OR PERSONS OR ENTITIES REFERENCING SERVICES ON THE WEBSITE, (b) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE COMPANY, (c) ANY UNAUTHORIZED ACCESS TO OR USE OF THE COMPANY&lsquo;S SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (d) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (e) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT (f) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR. THE COMPANY DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE COMPANY WEBSITE OR ANY LINKED WEBSITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND COMPANY WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE. THE SITE, ITS CONTENT AND ANYTHING CONTAINED ON THE SITE ARE DELIVERED STRICTLY IN &ldquo;AS IS&ldquo; CONDITION WITHOUT ANY TYPE OF WARRANTY.</p>
            <p>9. Limitation of Liability. EXCEPT WHERE PROHIBITED BY LAW, NEITHER zimbacash.com d/b/a zimbacash.com , NOR ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, INDEPENDENT CONTRACTORS, THIRD PARTY COLLECTORS, SUCCESSORS OR ASSIGNS OF EACH, SHALL BE LIABLE TO YOU FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS UNLESS OTHERWISE EXPRESSLY SET FORTH IN A WRITTEN AGREEMENT WITH YOU, zimbacash.com d/b/a zimbacash.com &lsquo;S MAXIMUM LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THIS SITE, OR ITS CONTENT, WHETHER IN CONTRACT, TORT OR OTHERWISE SHALL BE LIMITED TO THE AMOUNT YOU PAID TO ACCESS THIS SITE. In the event that the jurisdiction or state does not permit a limitation of liability as set forth above, then this limitation may not be applicable.</p>
            <p>
            10. Indemnification for Site Use. By using the Site, you agree to defend, indemnify, and hold harmless zimbacash.com d/b/a zimbacash.com from and against any and all losses, claims, damages, costs and expenses (including reasonable legal and expert fees) that zimbacash.com d/b/a zimbacash.com may become obligated to pay arising or resulting from your use of this Site, the Content, or your breach of these Terms and Conditions.
            </p>
            <p>
            11. Intellectual Property. This Site, the content, any materials downloaded, and any and all intellectual property pertaining to or contained on the Site (including but not limited to copyrights, patents, database rights, graphics, content, designs, text, logos, trademarks, service marks) are owned by zimbacash.com d/b/a zimbacash.com or third parties and all rights, titles and interests therein shall remain the property of zimbacash.com d/b/a zimbacash.com and/or such third parties (collectively, the &ldquo;Content&ldquo;). You agree that you will not duplicate, publish, modify, create derivative works from, participate in the transfer of, post on the World Wide Web, or in any way distribute or exploit the Site, or any portion of the Site for any public or commercial use without the express written consent of zimbacash.com d/b/a zimbacash.com. Furthermore, you agree that you will not (i) remove or alter any author, trademark or other proprietary notice or legend displayed on the Site (or printed pages produced from the Site); and (ii) make any other modifications to any documents obtained from the Site other than in connection with completing information required to transact business with zimbacash.com d/b/a zimbacash.com. All Content is protected by copyright and/or patent, trademark laws and various other intellectual property rights and unfair competition laws. You are authorized solely to view and retain a copy of the pages of the Site for your own personal and not for any type of commercial use. You may also view and make copies of relevant documents, pages, images or other materials on this Site for the purpose of transacting business with zimbacash.com d/b/a zimbacash.com only and not other purpose.
            </p>
            <p>12. Links. This Site may contain links to sites maintained by third parties. zimbacash.com d/b/a zimbacash.com is not responsible for the content, terms and conditions or privacy policies of those sites. Any such links should not be considered an endorsement or recommendation of those sites or of any product or service offered on those sites or of any party that is associated with those sites. Please note that other web sites and web pages linked to this Site may have their own or be governed by separate terms and conditions, including privacy policies. Please refer to the applicable terms and conditions of those web sites and web pages when visiting them.</p>
            <p>13. Persons under 18. This Site should not be accessed by persons under the age of 18.</p>
        </Container>
    )
}